pb/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, patterns, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^accounts/login/$', 'django.contrib.auth.views.login',
                           {'template_name': 'login.html'}),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'next_page': '/'}),

                       url(r'^api/test_executor/', include('test_executor.urls.api')),
                       url('^test_executor', include('test_executor.urls.ui')),

                       url('^$', 'pb.views.index', name="index"))

test_executor/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django_enumfield import enum


class Status(enum.Enum):
    PASS = 0
    FAIL = 1
    RUNNING = 2


class Run(models.Model):
    requester = models.ForeignKey(User)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    status = enum.EnumField(Status, default=Status.RUNNING)
    environment_id = models.PositiveSmallIntegerField()
    output = models.TextField(blank=True, null=True)


class Test(models.Model):
    run = models.ForeignKey(Run)
    file_name = models.CharField(max_length=2048)

pb/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import ensure_csrf_cookie


@login_required
@ensure_csrf_cookie
def index(request):
    context = RequestContext(request)
    return render_to_response('index.html', context)

test_executor/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import ensure_csrf_cookie

from test_executor.models import Run


@login_required
@ensure_csrf_cookie
def overview(request):
    context = RequestContext(request)
    return render_to_response('overview.html', context)


@login_required
def detail(request, run_id):
    context = RequestContext(request)
    try:
        context['run'] = Run.objects.get(id=run_id)
    except Run.DoesNotExist:
        pass

    return render_to_response('detail.html', context)

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="de">
    <head>
        <meta charset="utf-8">
        <!-- avoid 404 on favicon request -->
        <link rel="shortcut icon" href="#" />
        <title>{{ title|default:"Test Executer" }}</title>
        <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        {% block extra_css %}
        {% endblock %}

        <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "angular/angular.min.js" %}"></script>
        {% block extra_js %}
        {% endblock %}
    </head>
    <body>
        {% include "navbar.html" %}
        {% block extra_content %}
        {% endblock %}
        <div class="container main">
            {% block content %}
            {% endblock %}
        </div><!-- /.container -->
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <a href="{% url 'test_execution_overview' %}">Test Execution</a>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img class="brand" src="{% static "img/logo.png" %}"/>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        Angemeldet als {{ user }} &#9733; Last Refresh: {% now "d.m.y H:i" %}
                    </li>
                    <li>
                        <a href="/logout/">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="/">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

test_executor/templates/detail.html
{% extends "base.html" %}
{% load static test_executor %}

{% block extra_css %}
    <link type="text/css" rel="stylesheet" href="{% static "css/detail.css" %}">
{% endblock %}

{% block content %}
{% if run %}
<a href="{% url 'test_execution_overview' %}">Back to the Test Execution Overview</a>
<h2>Details - Test Execution: {{ run.id }}</h2>

<dl class="dl-horizontal">
    <dt>ID</dt><dd>{{ run.id }}</dd>
    <dt>Environment ID</dt><dd>{{ run.environment_id }}</dd>
    <dt>Requester</dt><dd>{{ run.requester }}</dd>
    <dt>Start Time</dt><dd>{{ run.start_time|date:"d.m.Y H:i:s" }}</dd>
    <dt>End Time</dt><dd>{{ run.end_time|date:"d.m.Y H:i:s" }}</dd>
    <dt>Status</dt><dd>{{ run.status|as_string }}</dd>
    <dt>Output</dt>
    <dd>
        <div class="bash">
            {{ run.output|as_html|safe }}
        </div>
    </dd>
    <dt>Used Files</dt>
    <dd>
        {% for test in run.test_set.all %}
            {{ test.file_name }}<br>
        {% empty %}
            No files available
        {% endfor %}
    </dd>
</dl>
{% else %}
    No details available for this test execution.
{% endif %}
{% endblock %}

test_executor/templates/info.html
{% load static %}
<script type="text/ng-template" id="info.html">
    <div class="modal-header">
        <h3 class="modal-title">How to use this interface?</h3>
    </div>
    <div class="modal-body">
        <ol>
            <li>Enter an environment id</li>
            <li>Choose a user as the requester</li>
            <li>Submit the form</li>
        </ol>

        <svg xmlns="http://www.w3.org/2000/svg">
            <circle cx="10" cy="10" r="10" fill="red" />
        </svg>
        <p class="pull-rigt">
            The red background color means that at least one of the tests FAILed.
        </p>

        <svg xmlns="http://www.w3.org/2000/svg">
            <circle cx="10" cy="10" r="10" fill="yellow" />
        </svg>
        <p class="pull-rigt">
            The yellow background color means that the test execution is running.
        </p>

        <svg xmlns="http://www.w3.org/2000/svg">
            <circle cx="10" cy="10" r="10" fill="#00ff40" />
        </svg>
        <p class="pull-rigt">
            The green background color means that all of the tests PASSed.
        </p>

  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">OK</button>
  </div>
</script>

test_executor/templates/overview.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static "css/overview.css" %}">
{% endblock %}

{% block extra_js %}
  <script src="{% static "angular-bootstrap/ui-bootstrap.min.js" %}"></script>
  <script src="{% static "angular-bootstrap/ui-bootstrap-tpls.min.js" %}"></script>

  <script src="{% static "js/app.js" %}"></script>
  <script src="{% static "js/run.ajax.js" %}"></script>
  <script src="{% static "js/run.data.js" %}"></script>
  <script src="{% static "js/user.ajax.js" %}"></script>
  <script src="{% static "js/user.data.js" %}"></script>
{% endblock %}

{% block content %}
<div ng-app="testRun" ng-controller="AppController as ctrl">
  <!-- Info Button -->
  <button id="info" class="btn btn-default pull-right" ng-click="ctrl.info()">
    <span class="glyphicon glyphicon-info-sign"></span>
  </button>

  <!-- Input Form -->
  <h2>Test Execution Requests</h2>
  <form ng-submit="ctrl.submit()">
      Test Environment (1-100) :
      <input class="form-control" type="number" ng-model="environment_id" min="1" max="100" required>

      Requester:
      <select class="form-control"
              ng-model="selectedUser"
              ng-options="user.full_name for user in list_of_users">
      </select>

      <button type="submit" class="btn btn-default btn-md">
        <span class="glyphicon glyphicon-flash"></span> Submit!
      </button>
  </form>

  <!-- Message Panel -->
  <div class="message alert" ng-class="{'alert-danger': error_occured, 'alert-success': !error_occured}"
                             ng-model="ctrl.message"
                             ng-show="message">
    {% verbatim %}
      {{ message }}
    {% endverbatim %}
  </div>

  <!-- Panel to display the test run results -->
  <div class="clear"></div>
  {% verbatim %}
  <div class="result-panel" ng-hide="loading">
    <table class="overview">
      <thead>
        <tr>
          <th>Request ID</th>
          <th>Requester</th>
          <th>Start</th>
          <th>End</th>
          <th>Test Environment</th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="run in list_of_runs" ng-class="{'alert-warning': run.status == 2,
                                                       'alert-danger': run.status == 1,
                                                       'alert-success': run.status == 0}">
          <td>
             <a class="detail" href="/test_executor/runs/{{ run.id }}/">{{ run.id }}</a>
          </td>
          <td>
            {{ users.get_full_name_by_id(run.requester) }}
          </td>
          <td>
            {{ run.start_time | date:'yyyy-MM-dd HH:mm:ss' }}
          </td>
          <td>
            {{ run.end_time | date:'yyyy-MM-dd HH:mm:ss' }}
          </td>
          <td>
            {{ run.environment_id }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  {% endverbatim %}

  <!-- Interface Information Modal -->
  {% include "info.html" %}

</div><!-- app -->
{% endblock %}